### ISSUE TITLE
Use ppa repo to install Python instead of build from source code

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/documentation#9]
Hello guys,

One suggestion regarding [Tutorial 1](https://github.com/kytos-ng/documentation/blob/master/tutorials/napps/development_environment_setup.rst) would be to use Ubuntu PPA repos instead of building Python 3.9 from source code. From a developer perspective, I believe having the simplest setup environment procedure is always better!

That would simplify the process to basically:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.9
```

Let me know what you guys think.

**Comment by viniarck** [comment]
Thanks for the suggestion, Italo. This landed a couple of months ago but we forgot to link to this issue here

https://github.com/kytos-ng/documentation/pull/12/files
